# Generated by Django 5.2.14 on 2026-06-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='observationrecord',
            new_name='audit_app_o_audit_y_434f0e_idx',
            old_name='audit_app_o_audit_y_3888de_idx',
        ),
        migrations.RenameIndex(
            model_name='observationrecord',
            new_name='audit_app_o_company_f9e7ae_idx',
            old_name='audit_app_o_company_eb9f4a_idx',
        ),
    ]
