# Generated by Django 5.2.14 on 2026-06-03 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0002_rename_audit_app_o_audit_y_3888de_idx_audit_app_o_audit_y_434f0e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم لوحة التحكم')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('report_id', models.CharField(max_length=64, unique=True, verbose_name='معرف التقرير')),
                ('html_file', models.CharField(max_length=512, verbose_name='مسار ملف HTML')),
                ('source_files', models.JSONField(blank=True, default=list, verbose_name='الملفات المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('upload_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard', to='audit_app.uploadsession', verbose_name='جلسة الرفع')),
            ],
            options={
                'verbose_name': 'لوحة تحكم',
                'verbose_name_plural': 'لوحات التحكم',
                'ordering': ['-created_at'],
                'permissions': [('can_upload_files', 'يمكنه رفع الملفات وإنشاء لوحات التحكم'), ('can_view_dashboards', 'يمكنه عرض لوحات التحكم')],
            },
        ),
    ]
