# Generated by Django 5.2.14 on 2026-06-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0003_add_dashboard_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylogo',
            options={'verbose_name': 'شعار شركة', 'verbose_name_plural': 'شعارات الشركات'},
        ),
        migrations.AlterModelOptions(
            name='observationrecord',
            options={'verbose_name': 'ملاحظة تدقيق', 'verbose_name_plural': 'ملاحظات التدقيق'},
        ),
        migrations.AlterModelOptions(
            name='reportartifact',
            options={'verbose_name': 'نتيجة تقرير', 'verbose_name_plural': 'نتائج التقارير'},
        ),
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'verbose_name': 'جلسة رفع', 'verbose_name_plural': 'جلسات الرفع'},
        ),
        migrations.AddField(
            model_name='dashboard',
            name='icon',
            field=models.CharField(choices=[('bi-bar-chart-line-fill', 'مخطط أعمدة'), ('bi-pie-chart-fill', 'مخطط دائري'), ('bi-graph-up-arrow', 'مخطط خطي / نمو'), ('bi-table', 'جدول بيانات'), ('bi-clipboard2-data-fill', 'تحليل بيانات'), ('bi-file-earmark-spreadsheet-fill', 'جداول بيانات'), ('bi-calculator-fill', 'مالي / محاسبي'), ('bi-building-fill', 'مؤسسي / شركات')], default='bi-bar-chart-line-fill', max_length=64, verbose_name='رمز اللوحة'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='template_type',
            field=models.CharField(choices=[('ai', 'لوحة تحليلية ذكية (AI Dashboard)')], default='ai', max_length=32, verbose_name='نوع النموذج'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='raw_data_json',
            field=models.TextField(blank=True, default='', verbose_name='بيانات الملف (JSON)'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='html_file',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='ملف HTML المخزن مؤقتاً'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='locale',
            field=models.CharField(default='ar', max_length=8),
        ),
    ]
