# Generated by Django 5.2.14 on 2026-06-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0004_add_raw_data_icon_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='قيمة داخلية بدون مسافات، مثل: ai', max_length=32, unique=True, verbose_name='رمز النوع (كود)')),
                ('name', models.CharField(help_text='الاسم الذي يظهر للمستخدمين', max_length=128, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('icon', models.CharField(default='bi-grid', help_text='مثال: bi-bar-chart-line-fill', max_length=64, verbose_name='أيقونة Bootstrap')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتيب العرض')),
            ],
            options={
                'verbose_name': 'نوع نموذج لوحة التحكم',
                'verbose_name_plural': 'أنواع نماذج لوحات التحكم',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
