# Generated by Django 5.2.14 on 2026-06-13 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


ATTACHMENT_KINDS = [
    "deck",
    "highRisk",
    "tgaViolations",
    "missingVehicle",
    "internalAuditQuarterly",
    "specialAssignment",
]

DEFAULT_COMPANIES = [
    {"code": "BTC", "name": "BTC"},
    {"code": "NAT", "name": "NAT"},
    {"code": "AUM", "name": "AUM"},
    {"code": "SACO", "name": "SACO"},
]


def seed_companies_and_dashboards(apps, schema_editor):
    Company = apps.get_model("audit_app", "Company")
    CompanyAttachmentSetting = apps.get_model("audit_app", "CompanyAttachmentSetting")
    Dashboard = apps.get_model("audit_app", "Dashboard")

    default_company = None
    for item in DEFAULT_COMPANIES:
        company, _ = Company.objects.get_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "excel_company_names": [item["code"]],
                "is_active": True,
            },
        )
        if default_company is None:
            default_company = company
        for kind in ATTACHMENT_KINDS:
            CompanyAttachmentSetting.objects.get_or_create(
                company=company,
                attachment_kind=kind,
                defaults={"is_enabled": True},
            )

    if default_company is not None:
        Dashboard.objects.filter(company__isnull=True).update(company=default_company)


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0010_dashboard_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Short identifier, e.g. BTC, NAT', max_length=32, unique=True, verbose_name='Company code')),
                ('name', models.CharField(max_length=255, verbose_name='Display name')),
                ('excel_company_names', models.JSONField(blank=True, default=list, help_text='Names accepted in the Excel Company column for this tenant (defaults to the company code if empty).', verbose_name='Excel company names')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAttachmentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_kind', models.CharField(choices=[('deck', 'Company wise Audit committee report'), ('highRisk', 'High Risk Observations & Emerging Risks'), ('tgaViolations', 'TGA Violations Report'), ('missingVehicle', 'Missing Vehicle Report'), ('internalAuditQuarterly', 'Internal Audit Quarterly Report'), ('specialAssignment', 'Special Assignment Report')], max_length=32, verbose_name='Attachment type')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Company attachment setting',
                'verbose_name_plural': 'Company attachment settings',
                'ordering': ['company__code', 'attachment_kind'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_upload', models.BooleanField(default=False, verbose_name='Can upload files and create dashboards')),
                ('can_view', models.BooleanField(default=False, verbose_name='Can view dashboards')),
                ('can_review', models.BooleanField(default=False, verbose_name='Can approve or reject dashboards')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Company membership',
                'verbose_name_plural': 'Company memberships',
                'ordering': ['company__code', 'user__username'],
            },
        ),
        migrations.AlterModelOptions(
            name='companylogo',
            options={'verbose_name': 'Company logo', 'verbose_name_plural': 'Company logos'},
        ),
        migrations.AlterModelOptions(
            name='dashboardtemplatetype',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Dashboard template type', 'verbose_name_plural': 'Dashboard template types'},
        ),
        migrations.AlterModelOptions(
            name='observationrecord',
            options={'verbose_name': 'Audit observation', 'verbose_name_plural': 'Audit observations'},
        ),
        migrations.AlterModelOptions(
            name='reportartifact',
            options={'verbose_name': 'Report artifact', 'verbose_name_plural': 'Report artifacts'},
        ),
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'verbose_name': 'Upload session', 'verbose_name_plural': 'Upload sessions'},
        ),
        migrations.RenameIndex(
            model_name='dashboardrejectionlog',
            new_name='audit_app_d_dashboa_b3e1f8_idx',
            old_name='audit_app_d_dashboa_6e8f2a_idx',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='html_file',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Cached HTML file'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='icon',
            field=models.CharField(choices=[('bi-bar-chart-line-fill', 'Bar chart'), ('bi-pie-chart-fill', 'Pie chart'), ('bi-graph-up-arrow', 'Line / growth chart'), ('bi-table', 'Data table'), ('bi-clipboard2-data-fill', 'Data analysis'), ('bi-file-earmark-spreadsheet-fill', 'Spreadsheet'), ('bi-calculator-fill', 'Finance / accounting'), ('bi-building-fill', 'Organization / companies')], default='bi-bar-chart-line-fill', max_length=64, verbose_name='Dashboard icon'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Dashboard name'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='report_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Report ID'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='source_files',
            field=models.JSONField(blank=True, default=list, verbose_name='Source files'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='template_type',
            field=models.CharField(choices=[('ai', 'AI analytical dashboard')], default='ai', max_length=32, verbose_name='Template type'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='upload_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard', to='audit_app.uploadsession', verbose_name='Upload session'),
        ),
        migrations.AlterField(
            model_name='dashboardtemplatetype',
            name='code',
            field=models.SlugField(help_text='Internal slug without spaces, e.g. ai', max_length=32, unique=True, verbose_name='Type code'),
        ),
        migrations.AlterField(
            model_name='dashboardtemplatetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dashboardtemplatetype',
            name='icon',
            field=models.CharField(default='bi-grid', help_text='Example: bi-bar-chart-line-fill', max_length=64, verbose_name='Bootstrap icon'),
        ),
        migrations.AlterField(
            model_name='dashboardtemplatetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='dashboardtemplatetype',
            name='name',
            field=models.CharField(help_text='Display name shown to users', max_length=128, verbose_name='Type name'),
        ),
        migrations.AlterField(
            model_name='dashboardtemplatetype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='raw_data_json',
            field=models.TextField(blank=True, default='', verbose_name='Raw file data (JSON)'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='audit_app.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='companyattachmentsetting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_settings', to='audit_app.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='audit_app.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='companyattachmentsetting',
            unique_together={('company', 'attachment_kind')},
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('user', 'company')},
        ),
        migrations.RunPython(seed_companies_and_dashboards, migrations.RunPython.noop),
    ]
