# Generated by Django 5.2.14 on 2026-06-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0013_companymembership_can_delete_drafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='can_view',
            field=models.BooleanField(default=False, help_text='View all published dashboards in this company.', verbose_name='Can view dashboards'),
        ),
    ]
