# Generated by Django 5.2.14 on 2026-06-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0015_repair_company_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_kind',
            field=models.CharField(choices=[('main', 'Main company'), ('subsidiary', 'Subsidiary')], default='main', max_length=16, verbose_name='Company type'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG, JPEG, or WebP. Required for all companies.', upload_to='company_logos/%Y/%m/', verbose_name='Company logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Required when the company type is Subsidiary.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='audit_app.company', verbose_name='Parent company'),
        ),
    ]
