# Generated by Django 5.2.14 on 2026-06-19 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0017_dashboard_workflow_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='company',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='dashboardrejectionlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='dashboardrejectionlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='dashboardrejectionlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='dashboardtemplatetype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='dashboardtemplatetype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='dashboardtemplatetype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='dashboardworkflowinstance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='dashboardworkflowinstance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='dashboardworkflowinstance',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='dashboardworkflowsteplog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='dashboardworkflowsteplog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='dashboardworkflowsteplog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='observationrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='observationrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='observationrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='reportartifact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='reportartifact',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='reportartifact',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by'),
        ),
        migrations.AddField(
            model_name='workflowtemplate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft deleted'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_kind',
            field=models.CharField(choices=[('main', 'Main company'), ('subsidiary', 'Subsidiary')], default='main', help_text='Main companies have their own dashboards and Excel uploads. Subsidiaries are registered only for Excel subcompany codes and logos.', max_length=16, verbose_name='Company type'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Version'),
        ),
    ]
