# Generated by Django 5.2.14 on 2026-06-20 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0018_admin_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationrecord',
            name='audit_year',
            field=models.CharField(blank=True, max_length=64, verbose_name='Audit year'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='ia_status',
            field=models.CharField(blank=True, max_length=128, verbose_name='IA status'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='observation_name',
            field=models.TextField(blank=True, verbose_name='Observation name'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='raw_row',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw row'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='subcompany',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subcompany'),
        ),
        migrations.AlterField(
            model_name='observationrecord',
            name='upload_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='audit_app.uploadsession', verbose_name='Upload session'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='columns',
            field=models.PositiveIntegerField(default=0, verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='report_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Report ID'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='report_version',
            field=models.CharField(max_length=64, verbose_name='Report version'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Rows'),
        ),
        migrations.AlterField(
            model_name='reportartifact',
            name='upload_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='audit_app.uploadsession', verbose_name='Upload session'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='content_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='Content hash'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='locale',
            field=models.CharField(default='ar', max_length=8, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='mode',
            field=models.CharField(default='ai', max_length=32, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='sheet_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sheet name'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='source_name',
            field=models.CharField(max_length=255, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at'),
        ),
    ]
