# Generated by Django 5.2.15 on 2026-06-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0019_alter_observationrecord_audit_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='template_type',
            field=models.CharField(choices=[('ai', 'AI analytical dashboard'), ('ar_compliance', 'Arabic compliance dashboard')], default='ai', max_length=32, verbose_name='Template type'),
        ),
    ]
