# Generated by Django 5.2.15 on 2026-06-21

from django.db import migrations, models

from audit_app.dashboard_template_codes import (
    DEFAULT_DASHBOARD_TEMPLATE_CODE,
    TEMPLATE_CODE_CD,
    TEMPLATE_CODE_IAD,
    seed_dashboard_template_types,
)


def migrate_template_codes_forward(apps, schema_editor):
    seed_dashboard_template_types(apps)


def migrate_template_codes_backward(apps, schema_editor):
    from audit_app.dashboard_template_codes import (
        LEGACY_TEMPLATE_CODE_CD,
        LEGACY_TEMPLATE_CODE_IAD,
        TEMPLATE_TYPE_SEEDS,
    )

    DashboardTemplateType = apps.get_model("audit_app", "DashboardTemplateType")
    Dashboard = apps.get_model("audit_app", "Dashboard")
    UploadSession = apps.get_model("audit_app", "UploadSession")

    legacy_seeds = [
        {
            "code": LEGACY_TEMPLATE_CODE_IAD,
            "name": "AI analytical dashboard",
            "description": TEMPLATE_TYPE_SEEDS[0]["description"],
            "icon": TEMPLATE_TYPE_SEEDS[0]["icon"],
            "sort_order": 1,
        },
        {
            "code": LEGACY_TEMPLATE_CODE_CD,
            "name": "Arabic compliance dashboard",
            "description": TEMPLATE_TYPE_SEEDS[1]["description"],
            "icon": TEMPLATE_TYPE_SEEDS[1]["icon"],
            "sort_order": 2,
        },
    ]

    DashboardTemplateType.objects.filter(code=TEMPLATE_CODE_IAD).update(
        code=LEGACY_TEMPLATE_CODE_IAD
    )
    DashboardTemplateType.objects.filter(code=TEMPLATE_CODE_CD).update(
        code=LEGACY_TEMPLATE_CODE_CD
    )

    Dashboard.objects.filter(template_type=TEMPLATE_CODE_IAD).update(
        template_type=LEGACY_TEMPLATE_CODE_IAD
    )
    Dashboard.objects.filter(template_type=TEMPLATE_CODE_CD).update(
        template_type=LEGACY_TEMPLATE_CODE_CD
    )
    UploadSession.objects.filter(mode=TEMPLATE_CODE_IAD).update(mode=LEGACY_TEMPLATE_CODE_IAD)
    UploadSession.objects.filter(mode=TEMPLATE_CODE_CD).update(mode=LEGACY_TEMPLATE_CODE_CD)

    for seed in legacy_seeds:
        code = seed["code"]
        defaults = {key: value for key, value in seed.items() if key != "code"}
        defaults["is_active"] = True
        DashboardTemplateType.objects.update_or_create(code=code, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("audit_app", "0020_add_ar_compliance_template_type"),
    ]

    operations = [
        migrations.RunPython(migrate_template_codes_forward, migrate_template_codes_backward),
        migrations.AlterField(
            model_name="dashboard",
            name="template_type",
            field=models.CharField(
                choices=[
                    (TEMPLATE_CODE_IAD, "Internal Audit Dashboard"),
                    (TEMPLATE_CODE_CD, "Compliance Dashboard"),
                ],
                default=DEFAULT_DASHBOARD_TEMPLATE_CODE,
                max_length=32,
                verbose_name="Template type",
            ),
        ),
        migrations.AlterField(
            model_name="uploadsession",
            name="mode",
            field=models.CharField(
                default=DEFAULT_DASHBOARD_TEMPLATE_CODE,
                max_length=32,
                verbose_name="Mode",
            ),
        ),
    ]
