"""
Bilingual UI string dictionary (Arabic / English) for all Django templates.

Usage:
    from web_strings import get_ui
    ui = get_ui("ar")   # or "en"
    ui["login_btn"]     # -> "دخول"
"""
from __future__ import annotations

_STRINGS: dict[str, dict[str, str]] = {
    "ar": {
        # ── Brand ────────────────────────────────
        "brand_name": "لوحة التدقيق",
        "brand_sub": "Excel Audit Dashboard",
        # ── Sidebar sections ─────────────────────
        "section_uploads": "رفع البيانات",
        "section_reports": "التقارير",
        "section_admin": "الإدارة",
        "section_account": "الحساب",
        # ── Sidebar links ─────────────────────────
        "nav_upload": "رفع الملفات",
        "nav_dashboards": "لوحات التحكم",
        "nav_admin": "لوحة الإدارة",
        "nav_profile": "الملف الشخصي",
        "nav_logout": "تسجيل الخروج",
        # ── Language toggle ───────────────────────
        "lang_toggle": "English",
        "lang_toggle_title": "Switch to English",
        # ── Login ─────────────────────────────────
        "login_page_title": "تسجيل الدخول — لوحة التدقيق",
        "login_title": "لوحة تحكم التدقيق",
        "login_subtitle": "Excel Audit Dashboard — تسجيل الدخول",
        "login_username": "اسم المستخدم",
        "login_username_ph": "أدخل اسم المستخدم",
        "login_password": "كلمة المرور",
        "login_password_ph": "أدخل كلمة المرور",
        "login_btn": "دخول",
        "login_no_reg": "لا يمكن إنشاء حساب جديد إلا عن طريق المسؤول",
        "login_error": "اسم المستخدم أو كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.",
        # ── Topbar ────────────────────────────────
        "topbar_date_prefix": "",
        # ── Dashboard list ────────────────────────
        "dl_page_title": "لوحات التحكم — لوحة التدقيق",
        "dl_heading": "لوحات التحكم المحفوظة",
        "dl_total_prefix": "إجمالي اللوحات المحفوظة:",
        "dl_new_btn": "إنشاء لوحة جديدة",
        "dl_date_label": "التاريخ:",
        "dl_by_label": "المنشئ:",
        "dl_empty_title": "لا توجد لوحات تحكم بعد",
        "dl_empty_sub_uploader": "ارفع ملف Excel لإنشاء أول لوحة تحكم",
        "dl_empty_sub_viewer": "لم يتم إنشاء أي لوحات تحكم حتى الآن",
        "dl_upload_btn": "رفع ملف",
        "dl_delete_btn": "حذف",
        "dl_delete_confirm": "هل تريد حذف لوحة التحكم «{name}»؟ لا يمكن التراجع عن هذا الإجراء.",
        "dl_delete_success": "تم حذف لوحة التحكم بنجاح.",
        "alert_no_delete_perm": "ليس لديك صلاحية حذف لوحات التحكم.",
        # ── Dashboard detail ──────────────────────
        "dd_page_title": "لوحة التدقيق",
        "dd_breadcrumb": "لوحات التحكم",
        "dd_open_new": "فتح في نافذة جديدة",
        "dd_new_btn": "لوحة جديدة",
        "dd_date_label": "التاريخ:",
        "dd_by_label": "المنشئ:",
        "dd_desc_label": "الوصف:",
        # ── Profile ───────────────────────────────
        "profile_page_title": "الملف الشخصي — لوحة التدقيق",
        "profile_heading": "الملف الشخصي",
        "profile_info_card": "معلومات الحساب",
        "profile_change_pw_card": "تغيير كلمة المرور",
        "profile_username": "اسم المستخدم",
        "profile_email": "البريد الإلكتروني",
        "profile_email_ph": "example@email.com",
        "profile_first_name": "الاسم الأول",
        "profile_first_name_ph": "الاسم الأول",
        "profile_last_name": "اسم العائلة",
        "profile_last_name_ph": "اسم العائلة",
        "profile_save_btn": "حفظ التغييرات",
        "profile_old_pw": "كلمة المرور الحالية",
        "profile_old_pw_ph": "أدخل كلمة المرور الحالية",
        "profile_new_pw": "كلمة المرور الجديدة",
        "profile_new_pw_ph": "8 أحرف على الأقل",
        "profile_confirm_pw": "تأكيد كلمة المرور الجديدة",
        "profile_confirm_pw_ph": "أعد إدخال كلمة المرور الجديدة",
        "profile_update_pw_btn": "تحديث كلمة المرور",
        "profile_saved_ok": "تم حفظ التغييرات بنجاح",
        "profile_pw_changed_ok": "تم تغيير كلمة المرور بنجاح",
        "profile_pw_wrong": "كلمة المرور الحالية غير صحيحة",
        "profile_pw_mismatch": "كلمتا المرور الجديدتان غير متطابقتين",
        "profile_pw_too_short": "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        "profile_role_staff": "Admin",
        "profile_role_user": "مستخدم",
        "profile_role": "الدور الوظيفي",
        "profile_joined": "تاريخ الانضمام",
        "profile_last_login": "آخر دخول",
        "profile_perms_card": "الصلاحيات",
        "profile_perm_upload": "رفع الملفات وإنشاء لوحات التحكم",
        "profile_perm_view": "عرض لوحات التحكم",
        # ── Upload form ───────────────────────────
        "upload_page_title": "رفع ملف جديد — لوحة التدقيق",
        "upload_heading": "رفع ملف Excel جديد",
        "upload_subheading": "سيتم تخزين بيانات الملف في قاعدة البيانات لعرضها لاحقاً كلوحة تحكم",
        "upload_name_label": "اسم لوحة التحكم",
        "upload_name_ph": "مثال: تقرير التدقيق الداخلي Q1 2026",
        "upload_name_required": "هذا الحقل مطلوب — أدخل اسماً مميزاً للوحة التحكم",
        "upload_icon_label": "رمز اللوحة",
        "upload_icon_hint": "اختر رمزاً يمثل نوع البيانات",
        "upload_template_label": "نوع لوحة التحكم",
        "upload_file_label": "ملفات Excel Workbook حسب الشركة",
        "upload_file_hint": "الصيغ المدعومة: .xlsx · .xls · .xlsm · .csv",
        "upload_file_required": "يرجى اختيار ملف Excel",
        "upload_sheet_label": "اسم الورقة (اختياري)",
        "upload_sheet_ph": "اتركه فارغاً للورقة الأولى",
        "upload_locale_label": "لغة تحليل البيانات",
        "upload_locale_ar": "العربية",
        "upload_locale_en": "الإنجليزية",
        "upload_desc_label": "وصف (اختياري)",
        "upload_desc_ph": "وصف مختصر لمحتوى هذه اللوحة",
        "upload_submit_btn": "حفظ وتحليل",
        "upload_processing": "جارٍ تحليل الملف وحفظ البيانات...",
        "upload_success": "تم رفع الملف بنجاح وحفظ البيانات في قاعدة البيانات!",
        "upload_err_name": "اسم لوحة التحكم مطلوب",
        "upload_err_icon": "يرجى اختيار رمز للوحة التحكم",
        "upload_err_file": "يرجى رفع ملف Excel",
        "upload_err_empty": "الملف فارغ أو لا يحتوي على بيانات",
        "upload_err_type": "نوع الملف غير مدعوم، يُرجى رفع ملف Excel أو CSV",
        "upload_icon_bar": "أعمدة",
        "upload_icon_pie": "دائري",
        "upload_icon_line": "خطي",
        "upload_icon_table": "جدول",
        "upload_icon_data": "بيانات",
        "upload_icon_sheet": "جداول",
        "upload_icon_finance": "مالي",
        "upload_icon_org": "مؤسسي",
        "upload_file_drop": "ملف Excel — اسحب هنا أو انقر للاختيار",
        "upload_deck_label": "تقرير لجنة المراجعة (اختياري — PPTX/PDF)",
        "upload_deck_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_high_risk_label": "ملاحظات المخاطر العالية والمخاطر الناشئة (اختياري — PPTX/PDF)",
        "upload_high_risk_hint": "ملف PowerPoint أو PDF واحد يُعرض في لوحة التحكم. التقارير بالإنجليزية فقط.",
        "upload_high_risk_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        # ── Dashboard detail: generation ─────────
        "dd_generating": "جارٍ إنشاء لوحة التحكم من قاعدة البيانات...",
        "dd_no_data": "لا توجد بيانات مخزنة لهذه اللوحة",
        # ── Alerts / messages ─────────────────────
        "alert_no_upload_perm": "ليس لديك صلاحية رفع الملفات.",
        "alert_no_view_perm": "ليس لديك صلاحية عرض لوحات التحكم.",
        # ── 403 ───────────────────────────────────
        "forbidden_title": "403 — غير مصرح",
        "forbidden_body": "ليس لديك صلاحية الوصول لهذه الصفحة.",
        "back_home": "العودة للرئيسية",
    },
    "en": {
        # ── Brand ────────────────────────────────
        "brand_name": "Audit Dashboard",
        "brand_sub": "Excel Audit Dashboard",
        # ── Sidebar sections ─────────────────────
        "section_uploads": "Data Upload",
        "section_reports": "Reports",
        "section_admin": "Administration",
        "section_account": "Account",
        # ── Sidebar links ─────────────────────────
        "nav_upload": "Upload Files",
        "nav_dashboards": "Dashboards",
        "nav_admin": "Admin Panel",
        "nav_profile": "My Profile",
        "nav_logout": "Sign Out",
        # ── Language toggle ───────────────────────
        "lang_toggle": "عربي",
        "lang_toggle_title": "التبديل إلى العربية",
        # ── Login ─────────────────────────────────
        "login_page_title": "Sign In — Audit Dashboard",
        "login_title": "Audit Dashboard",
        "login_subtitle": "Excel Audit Dashboard — Sign In",
        "login_username": "Username",
        "login_username_ph": "Enter your username",
        "login_password": "Password",
        "login_password_ph": "Enter your password",
        "login_btn": "Sign In",
        "login_no_reg": "New accounts are created by the Administrator only",
        "login_error": "Invalid username or password. Please try again.",
        # ── Topbar ────────────────────────────────
        "topbar_date_prefix": "",
        # ── Dashboard list ────────────────────────
        "dl_page_title": "Dashboards — Audit Dashboard",
        "dl_heading": "Saved Dashboards",
        "dl_total_prefix": "Total saved dashboards:",
        "dl_new_btn": "Create New Dashboard",
        "dl_date_label": "Date:",
        "dl_by_label": "Created by:",
        "dl_empty_title": "No dashboards yet",
        "dl_empty_sub_uploader": "Upload an Excel file to create your first dashboard",
        "dl_empty_sub_viewer": "No dashboards have been created yet",
        "dl_upload_btn": "Upload File",
        "dl_delete_btn": "Delete",
        "dl_delete_confirm": "Delete dashboard «{name}»? This cannot be undone.",
        "dl_delete_success": "Dashboard deleted successfully.",
        "alert_no_delete_perm": "You do not have permission to delete dashboards.",
        # ── Dashboard detail ──────────────────────
        "dd_page_title": "Audit Dashboard",
        "dd_breadcrumb": "Dashboards",
        "dd_open_new": "Open in New Window",
        "dd_new_btn": "New Dashboard",
        "dd_date_label": "Date:",
        "dd_by_label": "Created by:",
        "dd_desc_label": "Description:",
        # ── Profile ───────────────────────────────
        "profile_page_title": "My Profile — Audit Dashboard",
        "profile_heading": "My Profile",
        "profile_info_card": "Account Information",
        "profile_change_pw_card": "Change Password",
        "profile_username": "Username",
        "profile_email": "Email Address",
        "profile_email_ph": "example@email.com",
        "profile_first_name": "First Name",
        "profile_first_name_ph": "First name",
        "profile_last_name": "Last Name",
        "profile_last_name_ph": "Last name",
        "profile_save_btn": "Save Changes",
        "profile_old_pw": "Current Password",
        "profile_old_pw_ph": "Enter your current password",
        "profile_new_pw": "New Password",
        "profile_new_pw_ph": "Minimum 8 characters",
        "profile_confirm_pw": "Confirm New Password",
        "profile_confirm_pw_ph": "Re-enter the new password",
        "profile_update_pw_btn": "Update Password",
        "profile_saved_ok": "Changes saved successfully",
        "profile_pw_changed_ok": "Password changed successfully",
        "profile_pw_wrong": "Current password is incorrect",
        "profile_pw_mismatch": "New passwords do not match",
        "profile_pw_too_short": "Password must be at least 8 characters",
        "profile_role_staff": "Admin",
        "profile_role_user": "User",
        "profile_role": "Role",
        "profile_joined": "Joined",
        "profile_last_login": "Last Login",
        "profile_perms_card": "Permissions",
        "profile_perm_upload": "Upload files & create dashboards",
        "profile_perm_view": "View dashboards",
        # ── Upload form ───────────────────────────
        "upload_page_title": "Upload New File — Audit Dashboard",
        "upload_heading": "Upload New Excel File",
        "upload_subheading": "File data will be stored in the database and displayed as a dashboard",
        "upload_name_label": "Dashboard Name",
        "upload_name_ph": "E.g.: Internal Audit Report Q1 2026",
        "upload_name_required": "This field is required — enter a unique dashboard name",
        "upload_icon_label": "Dashboard Icon",
        "upload_icon_hint": "Choose an icon that represents the data type",
        "upload_template_label": "Dashboard Template",
        "upload_file_label": "Company wise Excel workbook files",
        "upload_file_hint": "Supported formats: .xlsx · .xls · .xlsm · .csv",
        "upload_file_required": "Please select an Excel file",
        "upload_sheet_label": "Sheet Name (optional)",
        "upload_sheet_ph": "Leave blank for the first sheet",
        "upload_locale_label": "Data Analysis Language",
        "upload_locale_ar": "Arabic",
        "upload_locale_en": "English",
        "upload_desc_label": "Description (optional)",
        "upload_desc_ph": "Brief description of this dashboard's content",
        "upload_submit_btn": "Save & Analyze",
        "upload_processing": "Analyzing file and saving data...",
        "upload_success": "File uploaded and data saved to the database successfully!",
        "upload_err_name": "Dashboard name is required",
        "upload_err_icon": "Please select a dashboard icon",
        "upload_err_file": "Please upload an Excel file",
        "upload_err_empty": "The file is empty or contains no data",
        "upload_err_type": "Unsupported file type — please upload an Excel or CSV file",
        "upload_icon_bar": "Bar",
        "upload_icon_pie": "Pie",
        "upload_icon_line": "Line",
        "upload_icon_table": "Table",
        "upload_icon_data": "Data",
        "upload_icon_sheet": "Spreadsheet",
        "upload_icon_finance": "Finance",
        "upload_icon_org": "Organization",
        "upload_file_drop": "Excel file — drag here or click to browse",
        "upload_deck_label": "Company wise Audit committee report (optional — PPTX/PDF)",
        "upload_deck_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_high_risk_label": "Company wise High Risk Observations & Emerging Risks (optional — PPTX/PDF)",
        "upload_high_risk_hint": "One PowerPoint or PDF file, shown in the dashboard when you open it. English reports only.",
        "upload_high_risk_drop": "PPTX or PDF file — drag here or click to browse",
        # ── Dashboard detail: generation ─────────
        "dd_generating": "Generating dashboard from database...",
        "dd_no_data": "No stored data for this dashboard",
        # ── Alerts / messages ─────────────────────
        "alert_no_upload_perm": "You do not have permission to upload files.",
        "alert_no_view_perm": "You do not have permission to view dashboards.",
        # ── 403 ───────────────────────────────────
        "forbidden_title": "403 — Forbidden",
        "forbidden_body": "You do not have permission to access this page.",
        "back_home": "Back to Home",
    },
}


def get_ui(lang: str) -> dict[str, str]:
    """Return UI string dict for the given language ('ar' or 'en')."""
    key = "ar" if str(lang).strip().lower() == "ar" else "en"
    return _STRINGS[key]
