"""
Bilingual UI string dictionary (Arabic / English) for all Django templates.

Usage:
    from web_strings import get_ui
    ui = get_ui("ar")   # or "en"
    ui["login_btn"]     # -> "دخول"
"""
from __future__ import annotations

_STRINGS: dict[str, dict[str, str]] = {
    "ar": {
        # ── Brand ────────────────────────────────
        "brand_name": "لوحة التدقيق",
        "brand_sub": "Audit Dashboard",
        # ── Sidebar sections ─────────────────────
        "section_uploads": "رفع البيانات",
        "section_reports": "التقارير",
        "section_admin": "الإدارة",
        "section_account": "الحساب",
        # ── Sidebar links ─────────────────────────
        "nav_upload": "رفع الملفات",
        "nav_dashboards": "لوحات التحكم",
        "nav_admin": "لوحة الإدارة",
        "nav_profile": "الملف الشخصي",
        "nav_logout": "تسجيل الخروج",
        # ── Language toggle ───────────────────────
        "lang_toggle": "English",
        "lang_toggle_title": "Switch to English",
        # ── Login ─────────────────────────────────
        "login_page_title": "تسجيل الدخول — لوحة التدقيق",
        "login_title": "لوحة تحكم التدقيق",
        "login_subtitle": "تسجيل الدخول",
        "login_username": "اسم المستخدم",
        "login_username_ph": "أدخل اسم المستخدم",
        "login_password": "كلمة المرور",
        "login_password_ph": "أدخل كلمة المرور",
        "login_btn": "دخول",
        "login_no_reg": "لا يمكن إنشاء حساب جديد إلا عن طريق المسؤول",
        "login_error": "اسم المستخدم أو كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.",
        "login_err_deleted": "تم تعطيل هذا الحساب.",
        "login_err_smtp": "التحقق عبر البريد غير متاح حالياً. تواصل مع المسؤول.",
        "login_err_no_email": "لا يوجد بريد إلكتروني مسجل لهذا الحساب.",
        "login_err_2fa_send": "تعذر إرسال رمز التحقق. حاول لاحقاً.",
        "login_err_rate_limit": "طلب تسجيل دخول قيد المعالجة. انتظر لحظات ثم حاول مجدداً.",
        "login_session_expired": "انتهت جلستك بسبب عدم النشاط. يرجى تسجيل الدخول مرة أخرى.",
        "login_btn_loading": "جاري تسجيل الدخول…",
        "login_warn_2fa_smtp_superuser": "التحقق عبر البريد غير متاح حالياً؛ تم تسجيل الدخول بدون التحقق بخطوتين.",
        "verify_2fa_page_title": "التحقق بخطوتين — لوحة التدقيق",
        "verify_2fa_title": "التحقق من هويتك",
        "verify_2fa_subtitle": "أدخل الرمز المرسل إلى {email}",
        "verify_2fa_code_label": "رمز التحقق",
        "verify_2fa_code_ph": "6 أرقام",
        "verify_2fa_submit": "تأكيد",
        "verify_2fa_resend": "إعادة إرسال الرمز",
        "verify_2fa_invalid": "رمز غير صالح أو منتهي الصلاحية.",
        "verify_2fa_resent": "تم إرسال رمز جديد.",
        "verify_2fa_submit_loading": "جاري التحقق…",
        "verify_2fa_resend_loading": "جاري الإرسال…",
        "verify_2fa_resend_cooldown": "يُرجى الانتظار {seconds} ثانية قبل إعادة الإرسال.",
        "verify_2fa_resend_rate_limit": "محاولات إعادة إرسال كثيرة. حاول لاحقاً.",
        "verify_2fa_rate_limit": "محاولات كثيرة. حاول لاحقاً.",
        "select_company_page_title": "اختيار الشركة — لوحة التدقيق",
        "select_company_title": "اختر الشركة",
        "select_company_subtitle": "اختر الشركة التي تريد العمل ضمنها",
        "select_company_submit": "متابعة",
        "company_switch_label": "الشركة النشطة",
        "company_switch_placeholder": "— اختر شركة —",
        "company_switch_success": "تم تبديل الشركة.",
        "company_switch_left_dashboard": "تم تبديل الشركة — تمت إعادتك إلى قائمة الداشبوردات.",
        "company_switch_invalid": "اختيار شركة غير صالح.",
        "company_none_assigned": "لم يتم تعيين أي شركة لهذا الحساب.",
        "setup_required_page_title": "إعداد النظام — لوحة التدقيق",
        "setup_required_title": "لم يتم إعداد أي شركة بعد",
        "setup_required_admin_body": "لا توجد شركات نشطة في النظام. يرجى إضافة شركة واحدة على الأقل من لوحة الإدارة قبل استخدام رفع الملفات أو لوحات التحكم.",
        "setup_required_admin_btn": "إضافة شركة في لوحة الإدارة",
        "setup_required_user_body": "النظام غير جاهز للاستخدام بعد. يرجى التواصل مع مسؤول النظام لإضافة شركتك وتعيين الصلاحيات.",
        "profile_force_password_title": "يجب تحديث كلمة المرور",
        "profile_force_password_body": "كلمة مرورك قديمة. قم بتعيين كلمة مرور جديدة للمتابعة.",
        "profile_active_company": "الشركة النشطة",
        "profile_perm_review": "الموافقة أو الرفض على لوحات التحكم",
        # ── Topbar ────────────────────────────────
        "topbar_date_prefix": "",
        # ── Dashboard list ────────────────────────
        "dl_page_title": "لوحات التحكم — لوحة التدقيق",
        "dl_heading": "لوحات التحكم المحفوظة",
        "dl_total_prefix": "إجمالي اللوحات المحفوظة:",
        "dl_new_btn": "إنشاء لوحة جديدة",
        "dl_date_label": "التاريخ:",
        "dl_by_label": "المنشئ:",
        "dl_empty_title": "لا توجد لوحات تحكم بعد",
        "dl_empty_sub_uploader": "ارفع ملف Excel لإنشاء أول لوحة تحكم",
        "dl_empty_sub_viewer": "لم يتم إنشاء أي لوحات تحكم حتى الآن",
        "dl_upload_btn": "رفع ملف",
        "dl_delete_btn": "إزالة",
        "dl_delete_confirm": "هل تريد إزالة لوحة التحكم «{name}»؟ يمكن للمسؤول استعادتها لاحقاً.",
        "dl_delete_success": "تمت إزالة لوحة التحكم (حذف ناعم).",
        "dl_delete_published_forbidden": "لا يمكن حذف لوحة تحكم منشورة (تمت الموافقة عليها).",
        "dl_trash_btn": "اللوحات المُزالة",
        "dl_active_btn": "اللوحات النشطة",
        "dl_trash_heading": "اللوحات المُزالة",
        "dl_trash_empty_title": "لا توجد لوحات مُزالة",
        "dl_trash_empty_sub": "اللوحات التي يزيلها المسؤول تظهر هنا ويمكن استعادتها.",
        "dl_restore_btn": "استعادة",
        "dl_restore_confirm": "هل تريد استعادة لوحة التحكم «{name}»؟",
        "dl_restore_success": "تمت استعادة لوحة التحكم بنجاح.",
        "dl_undo_btn": "تراجع",
        "dl_undo_message": "تمت إزالة «{name}»",
        "dl_undo_success": "تم التراجع عن الإزالة.",
        "dl_undo_expired": "انتهت مهلة التراجع عن الإزالة.",
        "dl_deleted_badge": "مُزالة",
        "alert_no_delete_perm": "ليس لديك صلاحية حذف لوحات التحكم.",
        "wf_status_draft": "مسودة",
        "wf_status_under_review": "قيد المراجعة",
        "wf_status_in_workflow": "قيد الاطلاع",
        "wf_status_published": "منشورة",
        "wf_status_rejected": "مرفوضة",
        "wf_submit_btn": "إرسال للمراجعة",
        "wf_submit_title": "إرسال للمراجعة",
        "wf_submit_confirm": "إرسال هذه اللوحة للمراجعة؟ لن تتمكن من تعديلها حتى تُرفض أو تُعاد.",
        "wf_submit_submit": "تأكيد الإرسال",
        "wf_submit_success": "تم إرسال اللوحة للمراجعة.",
        "wf_submit_forbidden": "لا يمكنك إرسال هذه اللوحة للمراجعة.",
        "wf_ack_btn": "تم الاطلاع",
        "wf_ack_title": "تأكيد الاطلاع",
        "wf_ack_confirm": "تأكيد الاطلاع وإرسال اللوحة للخطوة التالية؟",
        "wf_ack_submit": "تأكيد الاطلاع",
        "wf_ack_success": "تم تسجيل اطلاعك.",
        "wf_ack_published": "اكتمل الاطلاع وتم نشر اللوحة.",
        "wf_ack_forbidden": "لا يمكنك تسجيل الاطلاع على هذه اللوحة.",
        "wf_workflow_started": "تمت الموافقة وبدء سير الاطلاع.",
        "wf_in_workflow": "اللوحة في سير الاطلاع.",
        "wf_use_acknowledge": "استخدم «تم الاطلاع» أثناء سير الاطلاع.",
        "wf_workflow_progress": "الخطوة {progress}",
        "wf_workflow_assignee": "بانتظار اطلاع: {name}",
        "wf_workflow_logs_title": "سجل الاطلاع",
        "dl_filter_all": "الكل",
        "dl_filter_pending_review": "بانتظار النشر",
        "dl_filter_published": "منشورة",
        "dl_filter_mine": "لوحاتي",
        "dl_filter_rejected": "مرفوضة",
        "dl_filter_draft": "مسودات",
        "dl_filter_empty": "لا توجد لوحات في هذا التصنيف.",
        "wf_approve_btn": "نشر",
        "wf_reject_btn": "رفض",
        "wf_approve_confirm": "هل تريد نشر هذه اللوحة؟",
        "wf_approve_title": "نشر اللوحة",
        "wf_approve_body": "هل تريد نشر لوحة «{name}»؟",
        "wf_approve_submit": "تأكيد النشر",
        "wf_reject_title": "رفض لوحة التحكم",
        "wf_reject_reason_label": "سبب الرفض",
        "wf_reject_reason_ph": "اكتب سبب الرفض للمنشئ…",
        "wf_reject_submit": "تأكيد الرفض",
        "wf_reject_logs_title": "سجل أسباب الرفض",
        "wf_reject_by": "بواسطة",
        "wf_resubmit_btn": "تعديل وإعادة الإرسال",
        "wf_resubmit_heading": "إعادة إرسال لوحة مرفوضة",
        "wf_resubmit_hint": "عدّل الملفات وأعد الحفظ كمسودة لمراجعة جديدة.",
        "upload_success_draft": "تم حفظ اللوحة كمسودة. أرسلها للمراجعة عند الجاهزية.",
        "wf_approve_success": "تم نشر اللوحة.",
        "wf_review_attach_title": "إدارة المرفقات (قبل الموافقة)",
        "wf_review_attach_hint": "يمكنك إضافة أو استبدال أو حذف المرفقات الاختيارية. ملف Excel الرئيسي غير قابل للتعديل هنا.",
        "wf_review_attach_save": "حفظ المرفقات",
        "wf_review_attach_saved": "تم تحديث المرفقات.",
        "wf_review_attach_error": "تعذّر تحديث المرفقات.",
        "wf_review_attach_forbidden": "لا يمكنك تعديل المرفقات لهذه اللوحة.",
        "wf_reject_success": "تم رفض اللوحة.",
        "wf_reject_reason_required": "سبب الرفض مطلوب.",
        "wf_review_forbidden": "ليس لديك صلاحية مراجعة اللوحات.",
        "wf_resubmit_success": "تم إعادة حفظ اللوحة كمسودة.",
        "wf_resubmit_forbidden": "لا يمكنك إعادة إرسال هذه اللوحة.",
        "wf_cancel": "إلغاء",
        "wf_dashboard_not_found": "لوحة التحكم غير موجودة.",
        "wf_already_rejected": "تم رفض هذه اللوحة مسبقاً.",
        "wf_already_published": "هذه اللوحة منشورة بالفعل.",
        "wf_review_not_pending": "هذه اللوحة ليست بانتظار المراجعة.",
        "dv_btn": "تعيين المشاهدين",
        "dv_title": "من يمكنه عرض هذه اللوحة؟",
        "dv_hint": "اختر أعضاء الشركة الذين يمكنهم عرض هذه اللوحة المنشورة.",
        "dv_save": "حفظ",
        "dv_saved": "تم حفظ تعيين المشاهدين.",
        "dv_forbidden": "ليس لديك صلاحية تعيين المشاهدين.",
        "dv_loading": "جاري التحميل…",
        "dv_empty": "لا يوجد أعضاء في هذه الشركة.",
        "dv_error": "تعذر حفظ التعيين. حاول مرة أخرى.",
        "dv_available": "المشاهدون المتاحون",
        "dv_chosen": "المشاهدون المختارون",
        "dv_available_help": "اختر الأسماء ثم اضغط السهم لإضافتهم إلى قائمة المشاهدين.",
        "dv_chosen_help": "اختر الأسماء ثم اضغط السهم لإزالتهم من قائمة المشاهدين.",
        "dv_filter": "تصفية",
        "dv_choose_all": "اختيار الكل",
        "dv_remove_all": "إزالة الكل",
        "dv_choose_selected": "إضافة المحدد",
        "dv_remove_selected": "إزالة المحدد",
        # ── Dashboard detail ──────────────────────
        "dd_page_title": "لوحة التدقيق",
        "dd_breadcrumb": "لوحات التحكم",
        "dd_open_new": "فتح في نافذة جديدة",
        "dd_new_btn": "لوحة جديدة",
        "dd_date_label": "التاريخ:",
        "dd_by_label": "المنشئ:",
        "dd_desc_label": "الوصف:",
        # ── Profile ───────────────────────────────
        "profile_page_title": "الملف الشخصي — لوحة التدقيق",
        "profile_heading": "الملف الشخصي",
        "profile_info_card": "معلومات الحساب",
        "profile_change_pw_card": "تغيير كلمة المرور",
        "profile_username": "اسم المستخدم",
        "profile_email": "البريد الإلكتروني",
        "profile_email_ph": "example@email.com",
        "profile_first_name": "الاسم الأول",
        "profile_first_name_ph": "الاسم الأول",
        "profile_last_name": "اسم العائلة",
        "profile_last_name_ph": "اسم العائلة",
        "profile_job_title": "المسمى الوظيفي",
        "profile_job_title_ph": "مثال: مدير التدقيق الداخلي",
        "profile_readonly_hint": "لتعديل بيانات الحساب، يرجى التواصل مع مسؤول النظام من لوحة الإدارة.",
        "profile_save_btn": "حفظ التغييرات",
        "profile_old_pw": "كلمة المرور الحالية",
        "profile_old_pw_ph": "أدخل كلمة المرور الحالية",
        "profile_new_pw": "كلمة المرور الجديدة",
        "profile_new_pw_ph": "8 أحرف على الأقل",
        "profile_confirm_pw": "تأكيد كلمة المرور الجديدة",
        "profile_confirm_pw_ph": "أعد إدخال كلمة المرور الجديدة",
        "profile_update_pw_btn": "تحديث كلمة المرور",
        "profile_saved_ok": "تم حفظ التغييرات بنجاح",
        "profile_pw_changed_ok": "تم تغيير كلمة المرور بنجاح",
        "profile_pw_wrong": "كلمة المرور الحالية غير صحيحة",
        "profile_pw_mismatch": "كلمتا المرور الجديدتان غير متطابقتين",
        "profile_pw_too_short": "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        # ── Set password (email link) ─────────────
        "set_password_page_title": "تعيين كلمة المرور — لوحة التدقيق",
        "set_password_heading": "تعيين كلمة المرور",
        "set_password_intro": "اختر كلمة مرور جديدة لحسابك.",
        "set_password_username_label": "اسم المستخدم",
        "set_password_submit": "حفظ كلمة المرور",
        "set_password_success": "تم تعيين كلمة المرور. يمكنك تسجيل الدخول الآن.",
        "set_password_invalid_link": "رابط تعيين كلمة المرور غير صالح أو منتهي الصلاحية. يرجى التواصل مع مسؤول النظام.",
        "set_password_go_login": "العودة لتسجيل الدخول",
        "profile_role_staff": "Admin",
        "profile_role_user": "مستخدم",
        "profile_role": "الدور الوظيفي",
        "profile_joined": "تاريخ الانضمام",
        "profile_last_login": "آخر دخول",
        "profile_perms_card": "الصلاحيات",
        "profile_perm_upload": "رفع الملفات وإنشاء لوحات التحكم",
        "profile_perm_view": "عرض لوحات التحكم",
        "profile_perm_delete": "سلة المحذوفات (سوبر أدمن فقط)",
        "profile_perm_delete_drafts": "حذف المسودات (حسب الشركة)",
        # ── Upload form ───────────────────────────
        "upload_page_title": "رفع ملف جديد — لوحة التدقيق",
        "upload_heading": "رفع ملف Excel جديد",
        "upload_subheading": "سيتم تخزين بيانات الملف في قاعدة البيانات لعرضها لاحقاً كلوحة تحكم",
        "upload_name_label": "اسم لوحة التحكم",
        "upload_name_ph": "مثال: تقرير التدقيق الداخلي Q1 2026",
        "upload_name_required": "هذا الحقل مطلوب — أدخل اسماً مميزاً للوحة التحكم",
        "upload_icon_label": "رمز اللوحة",
        "upload_icon_hint": "اختر رمزاً يمثل نوع البيانات",
        "upload_template_label": "نوع لوحة التحكم",
        "upload_err_template": "يرجى اختيار نوع لوحة التحكم",
        "upload_file_label": "ملفات Excel Workbook حسب الشركة",
        "upload_file_hint": "الصيغ المدعومة: .xlsx · .xls · .xlsm · .csv",
        "upload_file_required": "يرجى اختيار ملف Excel",
        "upload_sheet_label": "اسم الورقة (اختياري)",
        "upload_sheet_ph": "اتركه فارغاً للورقة الأولى",
        "upload_locale_label": "لغة تحليل البيانات",
        "upload_locale_ar": "العربية",
        "upload_locale_en": "الإنجليزية",
        "upload_desc_label": "وصف (اختياري)",
        "upload_desc_ph": "وصف مختصر لمحتوى هذه اللوحة",
        "upload_submit_btn": "حفظ وتحليل",
        "upload_processing": "جارٍ تحليل الملف وحفظ البيانات...",
        "upload_success": "تم رفع الملف بنجاح وحفظ البيانات في قاعدة البيانات!",
        "upload_err_name": "اسم لوحة التحكم مطلوب",
        "upload_err_icon": "يرجى اختيار رمز للوحة التحكم",
        "upload_err_file": "يرجى رفع ملف Excel",
        "upload_err_empty": "الملف فارغ أو لا يحتوي على بيانات",
        "upload_err_type": "نوع الملف غير مدعوم، يُرجى رفع ملف Excel أو CSV",
        "upload_icon_bar": "أعمدة",
        "upload_icon_pie": "دائري",
        "upload_icon_line": "خطي",
        "upload_icon_table": "جدول",
        "upload_icon_data": "بيانات",
        "upload_icon_sheet": "جداول",
        "upload_icon_finance": "مالي",
        "upload_icon_org": "مؤسسي",
        "upload_file_drop": "ملف Excel — اسحب هنا أو انقر للاختيار",
        "upload_deck_label": "تقرير لجنة المراجعة (اختياري — PPTX/PDF)",
        "upload_deck_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_high_risk_label": "ملاحظات المخاطر العالية والمخاطر الناشئة (اختياري — PPTX/PDF)",
        "upload_high_risk_hint": "ملف PowerPoint أو PDF واحد يُعرض في لوحة التحكم. التقارير بالإنجليزية فقط.",
        "upload_high_risk_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_tga_violations_label": "تقرير مخالفات TGA (اختياري — PPTX/PDF)",
        "upload_tga_violations_hint": "ملف PowerPoint أو PDF واحد يُعرض في لوحة التحكم. التقارير بالإنجليزية فقط.",
        "upload_tga_violations_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_missing_vehicle_label": "تقرير المركبات المفقودة (اختياري — PPTX/PDF)",
        "upload_missing_vehicle_hint": "ملف PowerPoint أو PDF واحد يُعرض في لوحة التحكم. التقارير بالإنجليزية فقط.",
        "upload_missing_vehicle_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_internal_audit_quarterly_label": "تقرير المراجعة الداخلية الربع سنوي (اختياري — PPTX/PDF)",
        "upload_internal_audit_quarterly_hint": "ملف PowerPoint أو PDF واحد يُعرض في لوحة التحكم. التقارير بالإنجليزية فقط.",
        "upload_internal_audit_quarterly_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_special_assignment_label": "تقرير المهام الخاصة (اختياري — PPTX/PDF)",
        "upload_special_assignment_hint": "ملف PowerPoint أو PDF واحد يُعرض في لوحة التحكم. التقارير بالإنجليزية فقط.",
        "upload_special_assignment_drop": "ملف PPTX أو PDF — اسحب هنا أو انقر للاختيار",
        "upload_attach_current": "مرفق حالي",
        "upload_attach_keep_hint": "اترك الحقل فارغاً للإبقاء على المرفق الحالي، أو اختر ملفاً جديداً للاستبدال.",
        "upload_attach_remove_btn": "حذف المرفق",
        "upload_attach_removed": "سيُحذف المرفق عند الحفظ",
        "upload_attach_replace_hint": "سيستبدل المرفق الحالي عند الحفظ",
        "upload_excel_removed_need_file": "تم حذف ملف Excel الحالي. ارفع ملف Excel بديلاً للمتابعة.",
        "wf_edit_draft_btn": "تعديل المسودة",
        "wf_edit_draft_heading": "تعديل لوحة مسودة",
        "wf_edit_draft_hint": "عدّل البيانات والمرفقات ثم احفظ. المرفقات الحالية تبقى ما لم تستبدلها أو تحذفها.",
        "wf_edit_draft_success": "تم حفظ تعديلات المسودة.",
        # ── Dashboard detail: generation ─────────
        "dd_generating": "جارٍ إنشاء لوحة التحكم من قاعدة البيانات...",
        "dd_no_data": "لا توجد بيانات مخزنة لهذه اللوحة",
        # ── Alerts / messages ─────────────────────
        "alert_no_upload_perm": "ليس لديك صلاحية رفع الملفات.",
        "alert_no_view_perm": "ليس لديك صلاحية عرض لوحات التحكم.",
        # ── 403 ───────────────────────────────────
        "forbidden_title": "403 — غير مصرح",
        "forbidden_body": "ليس لديك صلاحية الوصول لهذه الصفحة.",
        "not_found_page_title": "404 — الصفحة غير موجودة",
        "not_found_title": "404 — الصفحة غير موجودة",
        "not_found_body": "اللوحة غير موجودة أو لا يمكنك الوصول إليها.",
        "not_found_dashboard_btn": "العودة إلى اللوحات",
        "back_home": "العودة للرئيسية",
    },
    "en": {
        # ── Brand ────────────────────────────────
        "brand_name": "Audit Dashboard",
        "brand_sub": "Audit Dashboard",
        # ── Sidebar sections ─────────────────────
        "section_uploads": "Data Upload",
        "section_reports": "Reports",
        "section_admin": "Administration",
        "section_account": "Account",
        # ── Sidebar links ─────────────────────────
        "nav_upload": "Upload Files",
        "nav_dashboards": "Dashboards",
        "nav_admin": "Admin Panel",
        "nav_profile": "My Profile",
        "nav_logout": "Sign Out",
        # ── Language toggle ───────────────────────
        "lang_toggle": "عربي",
        "lang_toggle_title": "التبديل إلى العربية",
        # ── Login ─────────────────────────────────
        "login_page_title": "Sign In — Audit Dashboard",
        "login_title": "Audit Dashboard",
        "login_subtitle": "Sign In",
        "login_username": "Username",
        "login_username_ph": "Enter your username",
        "login_password": "Password",
        "login_password_ph": "Enter your password",
        "login_btn": "Sign In",
        "login_no_reg": "New accounts are created by the Administrator only",
        "login_error": "Invalid username or password. Please try again.",
        "login_err_deleted": "This account has been deactivated.",
        "login_err_smtp": "Email verification is unavailable. Contact your administrator.",
        "login_err_no_email": "No email address is registered for this account.",
        "login_err_2fa_send": "Could not send verification code. Try again later.",
        "login_err_rate_limit": "A sign-in request is already in progress. Wait a moment and try again.",
        "login_session_expired": "Your session ended due to inactivity. Please sign in again.",
        "login_btn_loading": "Signing in…",
        "login_warn_2fa_smtp_superuser": "Email verification is unavailable; signed in without two-factor authentication.",
        "verify_2fa_page_title": "Two-Factor Verification — Audit Dashboard",
        "verify_2fa_title": "Verify your identity",
        "verify_2fa_subtitle": "Enter the code sent to {email}",
        "verify_2fa_code_label": "Verification code",
        "verify_2fa_code_ph": "6 digits",
        "verify_2fa_submit": "Confirm",
        "verify_2fa_resend": "Resend code",
        "verify_2fa_invalid": "Invalid or expired code.",
        "verify_2fa_resent": "A new code was sent.",
        "verify_2fa_submit_loading": "Verifying…",
        "verify_2fa_resend_loading": "Sending…",
        "verify_2fa_resend_cooldown": "Please wait {seconds} seconds before resending.",
        "verify_2fa_resend_rate_limit": "Too many resend attempts. Try again later.",
        "verify_2fa_rate_limit": "Too many attempts. Try again later.",
        "select_company_page_title": "Select Company — Audit Dashboard",
        "select_company_title": "Select company",
        "select_company_subtitle": "Choose the company you want to work in",
        "select_company_submit": "Continue",
        "company_switch_label": "Active company",
        "company_switch_placeholder": "— Select company —",
        "company_switch_success": "Company switched.",
        "company_switch_left_dashboard": "Company switched — returned to the dashboard list.",
        "company_switch_invalid": "Invalid company selection.",
        "company_none_assigned": "No company access has been assigned to this account.",
        "setup_required_page_title": "System Setup — Audit Dashboard",
        "setup_required_title": "No company has been configured yet",
        "setup_required_admin_body": "There are no active companies in the system. Add at least one company in the Admin panel before using uploads or dashboards.",
        "setup_required_admin_btn": "Add company in Admin",
        "setup_required_user_body": "The system is not ready yet. Contact your administrator to add your company and assign permissions.",
        "profile_force_password_title": "Password update required",
        "profile_force_password_body": "Your password is older. Set a new password to continue.",
        "profile_active_company": "Active company",
        "profile_perm_review": "Approve or reject dashboards",
        # ── Topbar ────────────────────────────────
        "topbar_date_prefix": "",
        # ── Dashboard list ────────────────────────
        "dl_page_title": "Dashboards — Audit Dashboard",
        "dl_heading": "Saved Dashboards",
        "dl_total_prefix": "Total saved dashboards:",
        "dl_new_btn": "Create New Dashboard",
        "dl_date_label": "Date:",
        "dl_by_label": "Created by:",
        "dl_empty_title": "No dashboards yet",
        "dl_empty_sub_uploader": "Upload an Excel file to create your first dashboard",
        "dl_empty_sub_viewer": "No dashboards have been created yet",
        "dl_upload_btn": "Upload File",
        "dl_delete_btn": "Remove",
        "dl_delete_confirm": "Remove dashboard «{name}»? An administrator can restore it later.",
        "dl_delete_success": "Dashboard removed (soft delete).",
        "dl_delete_published_forbidden": "Published dashboards cannot be deleted.",
        "dl_trash_btn": "Removed dashboards",
        "dl_active_btn": "Active dashboards",
        "dl_trash_heading": "Removed dashboards",
        "dl_trash_empty_title": "No removed dashboards",
        "dl_trash_empty_sub": "Dashboards removed by an administrator appear here and can be restored.",
        "dl_restore_btn": "Restore",
        "dl_restore_confirm": "Restore dashboard «{name}»?",
        "dl_restore_success": "Dashboard restored successfully.",
        "dl_undo_btn": "Undo",
        "dl_undo_message": "Removed «{name}»",
        "dl_undo_success": "Deletion undone.",
        "dl_undo_expired": "The undo window has expired.",
        "dl_deleted_badge": "Removed",
        "alert_no_delete_perm": "You do not have permission to delete dashboards.",
        "wf_status_draft": "Draft",
        "wf_status_under_review": "Under review",
        "wf_status_in_workflow": "In workflow",
        "wf_status_published": "Published",
        "wf_status_rejected": "Rejected",
        "wf_submit_btn": "Submit for review",
        "wf_submit_title": "Submit for review",
        "wf_submit_confirm": "Submit this dashboard for review? You cannot edit it until it is rejected.",
        "wf_submit_submit": "Confirm submit",
        "wf_submit_success": "Dashboard submitted for review.",
        "wf_submit_forbidden": "You cannot submit this dashboard for review.",
        "wf_ack_btn": "Reviewed",
        "wf_ack_title": "Confirm review",
        "wf_ack_confirm": "Confirm review and forward to the next step?",
        "wf_ack_submit": "Confirm review",
        "wf_ack_success": "Review recorded.",
        "wf_ack_published": "Workflow complete. Dashboard published.",
        "wf_ack_forbidden": "You cannot review this dashboard.",
        "wf_workflow_started": "Approved. Review workflow started.",
        "wf_in_workflow": "This dashboard is in the review workflow.",
        "wf_use_acknowledge": "Use Reviewed during the workflow.",
        "wf_workflow_progress": "Step {progress}",
        "wf_workflow_assignee": "Awaiting review: {name}",
        "wf_workflow_logs_title": "Review log",
        "dl_filter_all": "All",
        "dl_filter_pending_review": "Needs my publish action",
        "dl_filter_published": "Published",
        "dl_filter_mine": "My dashboards",
        "dl_filter_rejected": "Rejected",
        "dl_filter_draft": "Drafts",
        "dl_filter_empty": "No dashboards in this filter.",
        "wf_approve_btn": "Publish",
        "wf_reject_btn": "Reject",
        "wf_approve_confirm": "Publish this dashboard?",
        "wf_approve_title": "Publish dashboard",
        "wf_approve_body": "Publish «{name}»?",
        "wf_approve_submit": "Confirm publish",
        "wf_reject_title": "Reject dashboard",
        "wf_reject_reason_label": "Rejection reason",
        "wf_reject_reason_ph": "Explain why this dashboard was rejected…",
        "wf_reject_submit": "Confirm rejection",
        "wf_reject_logs_title": "Rejection history",
        "wf_reject_by": "By",
        "wf_resubmit_btn": "Edit & resubmit",
        "wf_resubmit_heading": "Resubmit rejected dashboard",
        "wf_resubmit_hint": "Update the files and save again as a draft for review.",
        "upload_success_draft": "Dashboard saved as draft. Submit for review when ready.",
        "wf_approve_success": "Dashboard published.",
        "wf_review_attach_title": "Manage attachments (before approval)",
        "wf_review_attach_hint": "You can add, replace, or remove optional attachments. The main Excel file cannot be changed here.",
        "wf_review_attach_save": "Save attachments",
        "wf_review_attach_saved": "Attachments updated.",
        "wf_review_attach_error": "Could not update attachments.",
        "wf_review_attach_forbidden": "You cannot edit attachments for this dashboard.",
        "wf_reject_success": "Dashboard rejected.",
        "wf_reject_reason_required": "Rejection reason is required.",
        "wf_review_forbidden": "You do not have permission to review dashboards.",
        "wf_resubmit_success": "Dashboard resubmitted as draft.",
        "wf_resubmit_forbidden": "You cannot resubmit this dashboard.",
        "wf_cancel": "Cancel",
        "wf_dashboard_not_found": "Dashboard not found.",
        "wf_already_rejected": "This dashboard was already rejected.",
        "wf_already_published": "This dashboard is already published.",
        "wf_review_not_pending": "This dashboard is not pending review.",
        "dv_btn": "Assign viewers",
        "dv_title": "Who can view this dashboard?",
        "dv_hint": "Select company members who can view this published dashboard.",
        "dv_save": "Save",
        "dv_saved": "Viewer assignments saved.",
        "dv_forbidden": "You do not have permission to assign viewers.",
        "dv_loading": "Loading…",
        "dv_empty": "No members in this company.",
        "dv_error": "Could not save assignments. Please try again.",
        "dv_available": "Available viewers",
        "dv_chosen": "Chosen viewers",
        "dv_available_help": "Choose viewers and click the arrow to add them.",
        "dv_chosen_help": "Choose viewers and click the arrow to remove them.",
        "dv_filter": "Filter",
        "dv_choose_all": "Choose all",
        "dv_remove_all": "Remove all",
        "dv_choose_selected": "Add selected",
        "dv_remove_selected": "Remove selected",
        # ── Dashboard detail ──────────────────────
        "dd_page_title": "Audit Dashboard",
        "dd_breadcrumb": "Dashboards",
        "dd_open_new": "Open in New Window",
        "dd_new_btn": "New Dashboard",
        "dd_date_label": "Date:",
        "dd_by_label": "Created by:",
        "dd_desc_label": "Description:",
        # ── Profile ───────────────────────────────
        "profile_page_title": "My Profile — Audit Dashboard",
        "profile_heading": "My Profile",
        "profile_info_card": "Account Information",
        "profile_change_pw_card": "Change Password",
        "profile_username": "Username",
        "profile_email": "Email Address",
        "profile_email_ph": "example@email.com",
        "profile_first_name": "First Name",
        "profile_first_name_ph": "First name",
        "profile_last_name": "Last Name",
        "profile_last_name_ph": "Last name",
        "profile_job_title": "Job Title",
        "profile_job_title_ph": "e.g. Internal Audit Manager",
        "profile_readonly_hint": "To update account details, contact your system administrator via the Admin Panel.",
        "profile_save_btn": "Save Changes",
        "profile_old_pw": "Current Password",
        "profile_old_pw_ph": "Enter your current password",
        "profile_new_pw": "New Password",
        "profile_new_pw_ph": "Minimum 8 characters",
        "profile_confirm_pw": "Confirm New Password",
        "profile_confirm_pw_ph": "Re-enter the new password",
        "profile_update_pw_btn": "Update Password",
        "profile_saved_ok": "Changes saved successfully",
        "profile_pw_changed_ok": "Password changed successfully",
        "profile_pw_wrong": "Current password is incorrect",
        "profile_pw_mismatch": "New passwords do not match",
        "profile_pw_too_short": "Password must be at least 8 characters",
        # ── Set password (email link) ─────────────
        "set_password_page_title": "Set Password — Audit Dashboard",
        "set_password_heading": "Set your password",
        "set_password_intro": "Choose a new password for your account.",
        "set_password_username_label": "Username",
        "set_password_submit": "Save password",
        "set_password_success": "Your password was set. You can sign in now.",
        "set_password_invalid_link": "This password link is invalid or has expired. Contact your administrator.",
        "set_password_go_login": "Back to sign in",
        "profile_role_staff": "Admin",
        "profile_role_user": "User",
        "profile_role": "Role",
        "profile_joined": "Joined",
        "profile_last_login": "Last Login",
        "profile_perms_card": "Permissions",
        "profile_perm_upload": "Upload files & create dashboards",
        "profile_perm_view": "View dashboards",
        "profile_perm_delete": "Trash / restore (superuser only)",
        "profile_perm_delete_drafts": "Delete drafts (per company)",
        # ── Upload form ───────────────────────────
        "upload_page_title": "Upload New File — Audit Dashboard",
        "upload_heading": "Upload New Excel File",
        "upload_subheading": "File data will be stored in the database and displayed as a dashboard",
        "upload_name_label": "Dashboard Name",
        "upload_name_ph": "E.g.: Internal Audit Report Q1 2026",
        "upload_name_required": "This field is required — enter a unique dashboard name",
        "upload_icon_label": "Dashboard Icon",
        "upload_icon_hint": "Choose an icon that represents the data type",
        "upload_template_label": "Dashboard Template",
        "upload_err_template": "Please select a dashboard template type",
        "upload_file_label": "Company wise Excel workbook files",
        "upload_file_hint": "Supported formats: .xlsx · .xls · .xlsm · .csv",
        "upload_file_required": "Please select an Excel file",
        "upload_sheet_label": "Sheet Name (optional)",
        "upload_sheet_ph": "Leave blank for the first sheet",
        "upload_locale_label": "Data Analysis Language",
        "upload_locale_ar": "Arabic",
        "upload_locale_en": "English",
        "upload_desc_label": "Description (optional)",
        "upload_desc_ph": "Brief description of this dashboard's content",
        "upload_submit_btn": "Save & Analyze",
        "upload_processing": "Analyzing file and saving data...",
        "upload_success": "File uploaded and data saved to the database successfully!",
        "upload_err_name": "Dashboard name is required",
        "upload_err_icon": "Please select a dashboard icon",
        "upload_err_file": "Please upload an Excel file",
        "upload_err_empty": "The file is empty or contains no data",
        "upload_err_type": "Unsupported file type — please upload an Excel or CSV file",
        "upload_icon_bar": "Bar",
        "upload_icon_pie": "Pie",
        "upload_icon_line": "Line",
        "upload_icon_table": "Table",
        "upload_icon_data": "Data",
        "upload_icon_sheet": "Spreadsheet",
        "upload_icon_finance": "Finance",
        "upload_icon_org": "Organization",
        "upload_file_drop": "Excel file — drag here or click to browse",
        "upload_deck_label": "Company wise Audit committee report (optional — PPTX/PDF)",
        "upload_deck_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_high_risk_label": "Company wise High Risk Observations & Emerging Risks (optional — PPTX/PDF)",
        "upload_high_risk_hint": "One PowerPoint or PDF file, shown in the dashboard when you open it. English reports only.",
        "upload_high_risk_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_tga_violations_label": "TGA Violations Report (optional — PPTX/PDF)",
        "upload_tga_violations_hint": "One PowerPoint or PDF file, shown in the dashboard when you open it. English reports only.",
        "upload_tga_violations_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_missing_vehicle_label": "Missing Vehicle Report (optional — PPTX/PDF)",
        "upload_missing_vehicle_hint": "One PowerPoint or PDF file, shown in the dashboard when you open it. English reports only.",
        "upload_missing_vehicle_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_internal_audit_quarterly_label": "Internal Audit Quarterly Report (optional — PPTX/PDF)",
        "upload_internal_audit_quarterly_hint": "One PowerPoint or PDF file, shown in the dashboard when you open it. English reports only.",
        "upload_internal_audit_quarterly_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_special_assignment_label": "Special Assignment Report (optional — PPTX/PDF)",
        "upload_special_assignment_hint": "One PowerPoint or PDF file, shown in the dashboard when you open it. English reports only.",
        "upload_special_assignment_drop": "PPTX or PDF file — drag here or click to browse",
        "upload_attach_current": "Current attachment",
        "upload_attach_keep_hint": "Leave empty to keep the current file, or choose a new file to replace it.",
        "upload_attach_remove_btn": "Remove attachment",
        "upload_attach_removed": "Attachment will be removed on save",
        "upload_attach_replace_hint": "Will replace the current attachment on save",
        "upload_excel_removed_need_file": "The current Excel file was removed. Upload a replacement Excel file to continue.",
        "wf_edit_draft_btn": "Edit draft",
        "wf_edit_draft_heading": "Edit draft dashboard",
        "wf_edit_draft_hint": "Update data and attachments, then save. Existing attachments are kept unless you replace or remove them.",
        "wf_edit_draft_success": "Draft changes saved.",
        # ── Dashboard detail: generation ─────────
        "dd_generating": "Generating dashboard from database...",
        "dd_no_data": "No stored data for this dashboard",
        # ── Alerts / messages ─────────────────────
        "alert_no_upload_perm": "You do not have permission to upload files.",
        "alert_no_view_perm": "You do not have permission to view dashboards.",
        # ── 403 ───────────────────────────────────
        "forbidden_title": "403 — Forbidden",
        "forbidden_body": "You do not have permission to access this page.",
        "not_found_page_title": "404 — Page not found",
        "not_found_title": "404 — Page not found",
        "not_found_body": "This dashboard does not exist or you no longer have access.",
        "not_found_dashboard_btn": "Back to dashboards",
        "back_home": "Back to Home",
    },
}


def get_ui(lang: str) -> dict[str, str]:
    """Return UI string dict for the given language ('ar' or 'en')."""
    key = "ar" if str(lang).strip().lower() == "ar" else "en"
    return _STRINGS[key]
