# Generated by Django 5.2.14 on 2026-06-13 18:35

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def backfill_profile_security_fields(apps, schema_editor):
    UserProfile = apps.get_model("accounts_app", "UserProfile")
    for profile in UserProfile.objects.select_related("user").iterator():
        if not profile.password_changed_at:
            profile.password_changed_at = profile.user.date_joined or timezone.now()
            profile.save(update_fields=["password_changed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_userprofile_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Password last changed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, a one-time code is sent by email at sign-in.', verbose_name='Email two-factor authentication'),
        ),
        migrations.RunPython(backfill_profile_security_fields, migrations.RunPython.noop),
    ]
