# Generated by Django 5.2.14 on 2026-06-13 19:44

from django.db import migrations, models


def disable_two_factor_for_all(apps, schema_editor):
    UserProfile = apps.get_model("accounts_app", "UserProfile")
    UserProfile.objects.filter(two_factor_enabled=True).update(two_factor_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_company_and_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, a one-time code is sent by email at sign-in. Disabled by default — enable per user or for all users from the admin.', verbose_name='Email two-factor authentication'),
        ),
        migrations.RunPython(disable_two_factor_for_all, migrations.RunPython.noop),
    ]
