# Generated by Django 5.2.14 on 2026-06-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0013_passwordsettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordsettoken',
            new_name='accounts_ap_user_id_edb777_idx',
            old_name='accounts_ap_user_id_6a8f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordsettoken',
            new_name='accounts_ap_expires_a971a3_idx',
            old_name='accounts_ap_expires_91b4e1_idx',
        ),
    ]
