"""URL routes for upload, dashboards, and /api/version."""

from django.urls import path
from django.views.generic import RedirectView

from .views import (
    analyze,
    api_version,
    dashboard_acknowledge,
    dashboard_approve,
    dashboard_detail,
    dashboard_delete,
    dashboard_list,
    dashboard_reject,
    dashboard_restore,
    dashboard_serve,
    dashboard_submit,
    favicon,
    index,
)
from .ar_compliance_views import (
    ar_api_aging_summary,
    ar_api_audit_plan_panel,
    ar_api_brand_logo,
    ar_api_export_dashboard_html,
    ar_api_export_legal_text_pptx,
    ar_api_legal_text_details,
    ar_api_legal_text_row_images,
    ar_api_send_legal_text_email,
    ar_api_summary,
)

urlpatterns = [
    path("", dashboard_list, name="dashboard_list"),
    path("upload/", index, name="upload"),
    path(
        "dashboards/",
        RedirectView.as_view(url="/", permanent=False),
        name="dashboard_list_legacy",
    ),
    path("analyze", analyze, name="analyze"),
    path("analyze/", analyze, name="analyze_slash"),
    path("api/version", api_version, name="api_version"),
    path("favicon.ico", favicon, name="favicon"),
    path("dashboards/<int:pk>/", dashboard_detail, name="dashboard_detail"),
    path("dashboards/<int:pk>/delete/", dashboard_delete, name="dashboard_delete"),
    path("dashboards/<int:pk>/restore/", dashboard_restore, name="dashboard_restore"),
    path("dashboards/<int:pk>/approve/", dashboard_approve, name="dashboard_approve"),
    path("dashboards/<int:pk>/reject/", dashboard_reject, name="dashboard_reject"),
    path("dashboards/<int:pk>/submit/", dashboard_submit, name="dashboard_submit"),
    path("dashboards/<int:pk>/acknowledge/", dashboard_acknowledge, name="dashboard_acknowledge"),
    path("dashboards/<int:pk>/serve/", dashboard_serve, name="dashboard_serve"),
    path("dashboards/<int:pk>/ar-api/summary", ar_api_summary, name="ar_api_summary"),
    path("dashboards/<int:pk>/ar-api/summary/", ar_api_summary, name="ar_api_summary_slash"),
    path("dashboards/<int:pk>/ar-api/aging-summary", ar_api_aging_summary, name="ar_api_aging_summary"),
    path("dashboards/<int:pk>/ar-api/aging-summary/", ar_api_aging_summary, name="ar_api_aging_slash"),
    path("dashboards/<int:pk>/ar-api/legal-text-details", ar_api_legal_text_details, name="ar_api_legal_details"),
    path("dashboards/<int:pk>/ar-api/legal-text-details/", ar_api_legal_text_details, name="ar_api_legal_details_slash"),
    path("dashboards/<int:pk>/ar-api/legal-text-row-images", ar_api_legal_text_row_images, name="ar_api_legal_images"),
    path("dashboards/<int:pk>/ar-api/legal-text-row-images/", ar_api_legal_text_row_images, name="ar_api_legal_images_slash"),
    path("dashboards/<int:pk>/ar-api/send-legal-text-email", ar_api_send_legal_text_email, name="ar_api_send_email"),
    path("dashboards/<int:pk>/ar-api/send-legal-text-email/", ar_api_send_legal_text_email, name="ar_api_send_email_slash"),
    path("dashboards/<int:pk>/ar-api/export-legal-text-pptx", ar_api_export_legal_text_pptx, name="ar_api_export_pptx"),
    path("dashboards/<int:pk>/ar-api/export-legal-text-pptx/", ar_api_export_legal_text_pptx, name="ar_api_export_pptx_slash"),
    path("dashboards/<int:pk>/ar-api/export-dashboard-html", ar_api_export_dashboard_html, name="ar_api_export_html"),
    path("dashboards/<int:pk>/ar-api/export-dashboard-html/", ar_api_export_dashboard_html, name="ar_api_export_html_slash"),
    path("dashboards/<int:pk>/ar-api/brand-logo", ar_api_brand_logo, name="ar_api_brand_logo"),
    path("dashboards/<int:pk>/ar-api/brand-logo/", ar_api_brand_logo, name="ar_api_brand_logo_slash"),
    path("dashboards/<int:pk>/ar-api/audit-plan-panel", ar_api_audit_plan_panel, name="ar_api_audit_plan"),
    path("dashboards/<int:pk>/ar-api/audit-plan-panel/", ar_api_audit_plan_panel, name="ar_api_audit_plan_slash"),
]
